# Generated by Django 5.2.1 on 2026-02-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('UPDATE', 'Update'), ('PUBLISH', 'Publish'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_name', models.CharField(blank=True, max_length=255)),
                ('visible_from', models.DateTimeField()),
                ('visible_until', models.DateTimeField()),
                ('is_active_manual', models.BooleanField(default=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_window', to='core.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(db_index=True, max_length=20)),
                ('room_no', models.CharField(max_length=50)),
                ('seat_no', models.CharField(max_length=50)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_start_time', models.DateTimeField()),
                ('other_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='core.uploadedfile')),
            ],
            options={
                'indexes': [models.Index(fields=['usn'], name='core_seatal_usn_58d482_idx')],
            },
        ),
    ]
